name: Update Databricks Notebooks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'notebooks/**'
      - '.github/workflows/notebooks.yaml'

jobs:
  deploy-databricks-notebooks:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_WORKSPACE_PATH: '/Shared/GitHub_Repo_Notebooks'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Deploy Databricks Notebooks
        run: |
          find notebooks -type f \( -name "*.py" -o -name "*.scala" -o -name "*.sql" -o -name "*.r" \) -print0 | while IFS= read -r -d $'\0' notebook_file; do
            echo "Processing notebook: $notebook_file"

            RELATIVE_PATH="${notebook_file#notebooks/}"
            TARGET_WORKSPACE_PATH="${DATABRICKS_WORKSPACE_PATH}/${RELATIVE_PATH}"
            TARGET_WORKSPACE_PATH=$(echo "${TARGET_WORKSPACE_PATH}" | sed 's#//#/#g')

            TARGET_DIR=$(dirname "${TARGET_WORKSPACE_PATH}")
            echo "Ensuring directory ${TARGET_DIR} exists in Databricks workspace..."
            databricks workspace mkdirs "${TARGET_DIR}" || echo "Target directory might already exist."

            echo "Importing ${notebook_file} to ${TARGET_WORKSPACE_PATH} ..."
            databricks workspace import --language "$(echo ${notebook_file##*.} | tr '[:lower:]' '[:upper:]')" --format SOURCE --overwrite "${notebook_file}" "${TARGET_WORKSPACE_PATH}"

            if [ $? -eq 0 ]; then
              echo "Successfully imported/updated ${TARGET_WORKSPACE_PATH}"
            else
              echo "Failed to import/update ${TARGET_WORKSPACE_PATH}"
              # Você pode querer falhar o workflow aqui, dependendo da sua necessidade
              # exit 1 
            fi
            echo "---"
          done
          echo "Notebook deployment process finished"
