name: Run Databricks Notebooks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'notebooks/**'
      - '.github/workflows/notebooks.yaml'

jobs:
  run-databricks-command:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Run Databricks command
        run: |
          databricks jobs create --json "$(cat jobs/binance_market_trades.json)"
